//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IronBox.AntiSQLi.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AntiSQLiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AntiSQLiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IronBox.AntiSQLi.Core.Resources.AntiSQLiResource", typeof(AntiSQLiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query arguments must not be null or empty.
        /// </summary>
        internal static string Error_InvalidQueryArguments {
            get {
                return ResourceManager.GetString("Error_InvalidQueryArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query text must not be null or empty.
        /// </summary>
        internal static string Error_InvalidQueryText {
            get {
                return ResourceManager.GetString("Error_InvalidQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no parameters parsed.
        /// </summary>
        internal static string Error_NoParametersParsed {
            get {
                return ResourceManager.GetString("Error_NoParametersParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert object to DbParameter.
        /// </summary>
        internal static string Error_ObjToDbParameterConversionError {
            get {
                return ResourceManager.GetString("Error_ObjToDbParameterConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine DbType for object.
        /// </summary>
        internal static string Error_UnableToAttainDbTypeForObject {
            get {
                return ResourceManager.GetString("Error_UnableToAttainDbTypeForObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parameterize query.
        /// </summary>
        internal static string Error_UnableToParameterizeQuery {
            get {
                return ResourceManager.GetString("Error_UnableToParameterizeQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse query arguments.
        /// </summary>
        internal static string Error_UnableToParseArguments {
            get {
                return ResourceManager.GetString("Error_UnableToParseArguments", resourceCulture);
            }
        }
    }
}
